# Generated by Django 4.2.7 on 2025-12-03 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(help_text='Token de Firebase Cloud Messaging para este dispositivo.', max_length=255, unique=True, verbose_name='Token FCM')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_ultimo_uso', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo de notificación',
                'verbose_name_plural': 'Dispositivos de notificación',
                'ordering': ['-fecha_ultimo_uso'],
            },
        ),
    ]
